// Local PostgreSQL WASM test. No Supabase connection, no real user data.
// npm install --prefix .tools/migration-test @electric-sql/pglite
import { PGlite } from '../.tools/migration-test/node_modules/@electric-sql/pglite/dist/index.js';
import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
const db = new PGlite();
const consolidated = process.argv.includes('--consolidated');
const statistics = process.argv.includes('--statistics');
process.on('uncaughtException', e => { console.error(e.message, e.where ?? ''); process.exit(1); });
const q = async (sql, args) => (await db.query(consolidated ? sql.replace(/\bmembers\b/g,'private.app_members') : sql, args)).rows;
const scalar = async (sql,args) => Object.values((await q(sql,args))[0])[0];
await db.exec(`
create role anon; create role authenticated; create role service_role;
create schema auth; create schema extensions;
create table auth.users(id uuid primary key, email text, is_anonymous boolean default true);
create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
create function auth.jwt() returns jsonb language sql stable as $$ select coalesce(nullif(current_setting('request.jwt.claims',true),''),'{}')::jsonb $$;
grant usage on schema auth to authenticated, anon, service_role;
create table public.players(id bigint generated by default as identity primary key,name text not null,current_mmr float8,mmr_rank bigint,
 total_pt float8,pt_rank bigint,history_highest_pt float8,history_highest_pt_rank bigint,games_played bigint,wins bigint,win_rate float8);
create table public.game_record(id uuid primary key,datetime bigint,p1 text,p2 text,p3 text,p4 text,p1score bigint,p2score bigint,p3score bigint,p4score bigint);
insert into public.players select n, 'Player '||n, 1400+n*3.25,n, 123.4+n,n,200+n,n,10+n,3,0.1234 from generate_series(1,99)n;
insert into public.game_record select gen_random_uuid(),202500000000,'Player 1','Player 2','Player 3','Player 4',10000,30000,25000,35000 from generate_series(1,1341);
alter table public.players enable row level security;
alter table public.game_record enable row level security;
grant select on public.players,public.game_record to authenticated;
`);
const original = await q(`select 'players' source,md5(jsonb_agg(to_jsonb(p) order by id)::text) digest from players p union all select 'games',md5(jsonb_agg(to_jsonb(g) order by id)::text) from game_record g`);
let bundle = await readFile(new URL('../build/legacy-migration/cutover.sql',import.meta.url),'utf8');
// gen_random_uuid is built into PostgreSQL; pgcrypto is not bundled in PGlite.
bundle = bundle.replace('create extension if not exists pgcrypto;', '');
try { await db.exec(bundle); } catch(e) { console.error('Migration:',e.message, e.position, e.where); throw e; }
if (consolidated) {
  // Reproduce the user's latest schema: fresh UUID primary key, no integer id.
  await db.exec('alter table players drop column id; alter table players add member_id uuid primary key default gen_random_uuid()');
  await db.exec(await readFile(new URL('../supabase/legacy/consolidate_players.sql',import.meta.url),'utf8'));
  assert.equal((await db.query("select to_regclass('public.members') v")).rows[0].v,null);
  assert.equal(await scalar("select count(*)::int from pg_constraint where contype='f' and confrelid='public.players'::regclass"),6);
}
assert.equal(await scalar('select count(*)::int from members'),99);
assert.equal(await scalar('select count(*)::int from games'),0);
assert.equal(await scalar("select to_regclass('public.legacy_games')"),null);
if(statistics) {
  const statsSql=await readFile(new URL('../supabase/legacy/auto_player_statistics.sql',import.meta.url),'utf8');
  await db.exec(statsSql);
  await db.exec(statsSql); // Reapplication must not duplicate hooks or totals.
}
const users = Array.from({length:5},()=>randomUUID());
for(const id of users) await q('insert into auth.users(id) values($1)',[id]);
const members = await q('select id,mmr,mmr_baseline from members order by legacy_player_id limit 4');
async function asUser(id, fn, claims={is_anonymous:true}) {
  await q("select set_config('request.jwt.claim.sub',$1,false),set_config('request.jwt.claims',$2,false)",[id,JSON.stringify(claims)]);
  await db.exec('set role authenticated');
  try { return await fn(); } finally { await db.exec('reset role'); }
}
const snapshot = await asUser(users[0],()=>scalar('select club_snapshot()'));
assert.equal(snapshot.members.length,99);
assert.equal(snapshot.games.length,0);
assert.equal(snapshot.members.find(m=>m.id===members[0].id).legacy_stats.total_pt,124.4);
await asUser(users[0],async()=> {
  assert.equal(await scalar('select count(*)::int from game_record'),0,'old RLS unchanged');
  await assert.rejects(()=>q('update members set mmr=0'),/permission denied/);
  await assert.rejects(()=>q('select * from private.member_carryovers'),/permission denied/);
  await assert.rejects(()=>q("select rename_room('7699','Hacked')"),/只有管理员/);
});
await asUser(users[4],()=>assert.rejects(()=>q('select club_snapshot()'),/不是俱乐部管理员/),{is_anonymous:false});
await db.exec('set role anon');
await assert.rejects(()=>q('select club_snapshot()'),/permission denied/);
await db.exec('reset role');
for(let i=0;i<4;i++) await asUser(users[i],async()=>{
  await q('select select_member($1)',[members[i].id]);
  await q('select sit_down($1,$2)',['7699',['east','south','west','north'][i]]);
});
async function newGame(scores) {
  const request=randomUUID();
  await asUser(users[0],async()=>{
    await q('select start_game($1,$2,$3)',['7699',request,null]);
    await q('select start_game($1,$2,$3)',['7699',request,null]);
  });
  const game=await scalar("select id from games where status='active'");
  await asUser(users[4],()=>assert.rejects(()=>q('select save_score($1,$2,$3,$4,$5)',[game,members[0].id,40000,0,randomUUID()]),/权限/));
  for(let i=0;i<4;i++) await asUser(users[i],()=>q('select save_score($1,$2,$3,$4,$5)',[game,members[i].id,scores[i],i,randomUUID()]));
  assert.equal(await scalar('select status from games where id=$1',[game]),'completed');
  return game;
}
const game1=await newGame([40000,30000,20000,10000]);
if(statistics) {
  const p=await scalar('select to_jsonb(p) from players p where member_id=$1',[members[0].id]);
  assert.equal(p.games_played,12); assert.equal(p.wins,4);
  assert.equal(p.win_rate,0.3333);
  assert.ok(p.total_pt>124.4);
}
const first=await q('select old_mmr,member_id from rating_settlement_players where settlement_id=(select id from rating_settlements where game_id=$1)',[game1]);
for(const row of first) assert.equal(row.old_mmr,members.find(m=>m.id===row.member_id).mmr);
const game2=await newGame([10000,20000,30000,40000]);
const beforeSecond=await q('select mmr from members order by legacy_player_id limit 4');
const corrected=Object.fromEntries(members.map((m,i)=>[m.id,[10000,30000,20000,40000][i]]));
await asUser(users[0],()=>q('select correct_scores($1,$2,$3,$4)',[game1,JSON.stringify(corrected),4,randomUUID()]));
assert.equal(await scalar('select max(revision) from rating_settlements where game_id=$1',[game1]),2);
assert.equal(await scalar('select max(revision) from rating_settlements where game_id=$1',[game2]),2);
assert.notDeepEqual(await q('select mmr from members order by legacy_player_id limit 4'),beforeSecond);
await assert.rejects(()=>q('update members set mmr_baseline=0'),/基线不可修改/);
await assert.rejects(()=>q("update private.member_carryovers set source='{}'"),/不可修改/);
const after=await q(`select 'players' source,md5(jsonb_agg(to_jsonb(p) order by ${consolidated?'member_id':'id'})::text) digest from players p union all select 'games',md5(jsonb_agg(to_jsonb(g) order by id)::text) from game_record g`);
if (consolidated) {
  assert.deepEqual(after.filter(r=>r.source==='games'),original.filter(r=>r.source==='games'),'old games unchanged');
  const originalColumns = await scalar(`select md5(jsonb_agg((to_jsonb(p)-ARRAY['member_id','normalized_name','mmr_baseline','created_at','current_mmr']) || jsonb_build_object('id',c.source_player_id,'current_mmr',(c.source->>'current_mmr')::float8) order by c.source_player_id)::text) from players p join private.member_carryovers c on c.member_id=p.member_id`);
  if(!statistics) assert.equal(originalColumns,original.find(r=>r.source==='players').digest);
  else {
    assert.equal(await scalar("select md5(jsonb_agg(source order by source_player_id)::text) from private.member_carryovers"),original.find(r=>r.source==='players').digest);
    const p=await scalar('select to_jsonb(p) from players p where member_id=$1',[members[0].id]);
    assert.equal(p.games_played,13); assert.equal(p.wins,3); assert.equal(p.win_rate,0.2308);
    assert.equal(await scalar('select wins from players where member_id=$1',[members[3].id]),5);
    const rows=await q('select * from players');
    for(const p of rows) {
      assert.equal(p.mmr_rank,1+rows.filter(x=>x.current_mmr>p.current_mmr).length);
      assert.equal(p.pt_rank,1+rows.filter(x=>x.total_pt>p.total_pt).length);
      assert.equal(p.history_highest_pt_rank,1+rows.filter(x=>x.history_highest_pt>p.history_highest_pt).length);
    }
    const before=await q('select * from players order by member_id');
    await db.exec('select private.refresh_player_statistics()');
    assert.deepEqual(await q('select * from players order by member_id'),before);
    const snap=await asUser(users[0],()=>scalar('select club_snapshot()'));
    for(const m of snap.members) {
      let tenths=Math.round(m.legacy_stats.total_pt*10);
      let peak=Math.max(tenths,Math.round(m.legacy_stats.history_highest_pt*10));
      const settled=snap.games.filter(g=>g.settlement).sort((a,b)=>a.settlement.order-b.settlement.order);
      for(const g of settled) {
        const result=g.settlement.players.find(x=>x.member_id===m.id);
        if(result) { tenths+=Math.round(result.pt*10); peak=Math.max(peak,tenths); }
      }
      assert.equal(m.current_stats.total_pt,tenths/10);
      assert.equal(m.current_stats.history_highest_pt,peak/10);
    }
    assert.equal(snap.members.find(m=>m.id===p.member_id).current_stats.total_pt,p.total_pt);
    assert.equal(snap.members.find(m=>m.id===p.member_id).legacy_stats.total_pt,124.4);
    await asUser(users[0],()=>assert.rejects(()=>q('select private.refresh_player_statistics()'),/permission denied/));
  }
  await asUser(users[4],()=>q("select create_member('NewPlayer')"));
  assert.equal(await scalar("select count(*)::int from players where name='NewPlayer' and normalized_name='newplayer' and current_mmr=1500 and mmr_baseline=1500 and total_pt=0"),1);
  await asUser(users[4],()=>assert.rejects(()=>q("select create_member('newplayer')"),/存在|使用/));
  await asUser(users[4],()=>assert.rejects(()=>q('update players set current_mmr=0'),/permission denied/));
  assert.equal(await scalar("select count(*)::int from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname in ('public','private') and position('public.members' in p.prosrc)>0"),0);
} else assert.deepEqual(after,original,'old tables are byte-for-byte equivalent as JSON');
await assert.rejects(()=>db.exec(bundle),/already exists/);
await db.exec('rollback');
assert.equal(await scalar('select count(*)::int from games'),2);
console.log('PASS: atomic cutover, 99 baselines, 1341 untouched old games, empty initial App history, RLS, RPC identity, two-game settlement/replay, immutable baselines, duplicate-request/rerun safety.');
await db.close();
